[deps]
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
